Remove unused usage of ftm
openebs/cstor-operators pull request #309
Opened 2021-05-04 14:09 UTC by soniasingla

Signed-off-by: Sonia Singla <soniasingla.1812@gmail.com>

2021-05-05 12:33 UTC, sonasingh46 approved these changes

2021-05-06 05:47 UTC, mittachaitu requested changes
Provided comments PTAL

2021-05-06 05:47 UTC, mittachaitu commented on pkg/pool/operations/create.go
> -		break
This `break` is required
 
**Context**: When the user specifies multiple `DataRaidGroups` first we will create a pool(at line 55 using 0th index raid group) and we will remove used RaidGroup from the total group list and then expand the pool.

2021-05-13 10:54 UTC, mittachaitu commented
@soniasingla Did you get a chance to incorporate review comments?

2021-05-21 19:17 UTC, soniasingla commented
@mittachaitu done sorry for delay

2021-05-25 15:11 UTC, merged