feat(e2e-test): Add E2E test cases for cstor csi
openebs/cstor-operators pull request #327
Opened 2021-05-06 05:16 UTC by nsathyaseelan

Signed-off-by: nsathyaseelan <sathyaseelan.n@mayadata.io>

- This PR is to Migrating the e2e tests for cstor operators from openebs/e2e-test repo into openebs/cstor-operator repo

2021-05-06 05:33 UTC, w3aman requested changes

2021-05-06 05:33 UTC, w3aman commented on e2e-tests/apps/busybox/deployers/run_e2e_test.yml
> +        args: ["-c", "ansible-playbook ./apps/busybox/deployers/test.yml -i /etc/ansible/hosts -v; exit 0"]
check path here
./e2e-tests/apps/*****

2021-05-06 05:33 UTC, w3aman commented on e2e-tests/apps/busybox/deployers/test.yml
> +        - include_tasks: /utils/fcm/update_litmus_result_resource.yml
change it at every place
/update_e2e_result_resource.yml

2021-05-06 05:33 UTC, w3aman commented on e2e-tests/apps/busybox/deployers/test.yml
> +        - include_tasks: /utils/fcm/update_litmus_result_resource.yml
check at every place, i think path will be now /e2e-tests/****

2021-05-06 05:33 UTC, w3aman commented on e2e-tests/apps/busybox/deployers/run_e2e_test.yml
> +        image: openebs/ansible-runner:ci
we need different image for this other than ansible-runner

2021-06-28 04:58 UTC, w3aman approved these changes
/looks good to me

2021-06-29 09:32 UTC, shubham14bajpai approved these changes
LGTM

2021-07-01 05:25 UTC, prateekpandey14 approved these changes
lgtm

2021-07-01 09:16 UTC, merged